### ISSUE TITLE
`syncIfPossible()` assertion failed

### ISSUE THREAD

**Issue by dusty-phillips** [dexie/Dexie.js#1409]
Dexie cloud has been rock solid for me lately, but I finally found an exciting new error. I've been playing around with realms and access control and probably set something up incorrectly.

Now I'm getting an assertion error in `syncIfPossible()`, with the following trace:

```
index.js:1 error in syncIfPossible() Error: Assertion Failed
    at assert (http://localhost:3000/static/js/vendors~main.chunk.js:60432:17)
    at Function.setByKeyPath (http://localhost:3000/static/js/vendors~main.chunk.js:60485:5)
    at http://localhost:3000/static/js/vendors~main.chunk.js:56521:75
    at Array.forEach (<anonymous>)
    at http://localhost:3000/static/js/vendors~main.chunk.js:56520:36
    at step (http://localhost:3000/static/js/vendors~main.chunk.js:50530:17)
    at Object.next (http://localhost:3000/static/js/vendors~main.chunk.js:50461:14)
    at step (http://localhost:3000/static/js/vendors~main.chunk.js:50469:133)
    at Object.next (http://localhost:3000/static/js/vendors~main.chunk.js:50461:14)
    at step (http://localhost:3000/static/js/vendors~main.chunk.js:50469:133)
    at Object.next (http://localhost:3000/static/js/vendors~main.chunk.js:50461:14)
    at fulfilled (http://localhost:3000/static/js/vendors~main.chunk.js:50415:24)
    at http://localhost:3000/static/js/vendors~main.chunk.js:61599:17
    at callListener (http://localhost:3000/static/js/vendors~main.chunk.js:61286:13)
    at endMicroTickScope (http://localhost:3000/static/js/vendors~main.chunk.js:61364:17)
    at http://localhost:3000/static/js/vendors~main.chunk.js:61430:24
    at IDBRequest.done (http://localhost:3000/static/js/vendors~main.chunk.js:63807:11)
From previous: 
    at __awaiter (http://localhost:3000/static/js/vendors~main.chunk.js:50412:10)
    at applyServerChanges (http://localhost:3000/static/js/vendors~main.chunk.js:56411:10)
    at http://localhost:3000/static/js/vendors~main.chunk.js:56283:23
    at step (http://localhost:3000/static/js/vendors~main.chunk.js:50530:17)
    at Object.next (http://localhost:3000/static/js/vendors~main.chunk.js:50461:14)
    at fulfilled (http://localhost:3000/static/js/vendors~main.chunk.js:50415:24)
    at http://localhost:3000/static/js/vendors~main.chunk.js:61599:17
    at callListener (http://localhost:3000/static/js/vendors~main.chunk.js:61286:13)
    at endMicroTickScope (http://localhost:3000/static/js/vendors~main.chunk.js:61364:17)
    at http://localhost:3000/static/js/vendors~main.chunk.js:61430:24
    at IDBRequest.req.onsuccess (http://localhost:3000/static/js/vendors~main.chunk.js:64027:20)
```

That's probably not much help since the line numbers are in the vendored package; I'm not sure how to tell Dexie to use local sources?

I deleted my local indexeddb and logged in again and am still getting the error. This suggests that whatever I messed up, it's managed to make its way to the cloud server. I figure that's pretty exciting from a beta testing standpoint. 

The cloud database in question is https://z7eizgr2b.dexie.cloud. 

Let me know what else I can give you to help debug.

**Comment by dfahlander** [comment]
Thanks a lot. It's obviously a bug. I'll look into it (hopefully tomorrow) and notify this issue when it's solved. Sorry for the inconvenience of having your db in this state until the issue is fixed.

**Comment by dfahlander** [comment]
👍

**Comment by dfahlander** [comment]
Thanks for your analysis! Seems as the server is stringifying the array keys, which could explain the invalid data.

**Comment by dfahlander** [comment]
This issue has been resolved.
