### ISSUE TITLE
Dexie-cloud-addon doesn't get along with vitejs

### ISSUE THREAD

**Issue by dusty-phillips** [dexie/Dexie.js#1484]
I'm trying to update my dexie-cloud backed app to use vitejs to take advantage of that sweet HMR response time. However, it's not getting along well with dexie-cloud.

I created a repro here: https://github.com/dusty-phillips/dexie-with-vite-repro, but will summarize in issue as well since I will probably delete that repo someday in a cleaning sweep:

```
yarn create vite dexie-vite-repro --template react-ts
cd dexie-vite-repro
```

Create a dexie-cloud instance using the normal documentation.

Run `yarn` and `yarn dev` to see the error message:

```
error when starting dev server:
Error: Build failed with 1 error:
node_modules/dexie-cloud-addon/dist/modern/dexie-cloud-addon.js:19:16: error: No matching export in "node_modules/dexie/dist/dexie.mjs" for import "cmp"
    at failureErrorWithLog (/Users/dustyphillips/Desktop/Code/dexie-vite-repro/node_modules/esbuild/lib/main.js:1493:15)
    at /Users/dustyphillips/Desktop/Code/dexie-vite-repro/node_modules/esbuild/lib/main.js:1151:28
    at runOnEndCallbacks (/Users/dustyphillips/Desktop/Code/dexie-vite-repro/node_modules/esbuild/lib/main.js:941:63)
    at buildResponseToResult (/Users/dustyphillips/Desktop/Code/dexie-vite-repro/node_modules/esbuild/lib/main.js:1149:7)
    at /Users/dustyphillips/Desktop/Code/dexie-vite-repro/node_modules/esbuild/lib/main.js:1258:14
    at /Users/dustyphillips/Desktop/Code/dexie-vite-repro/node_modules/esbuild/lib/main.js:629:9
    at handleIncomingPacket (/Users/dustyphillips/Desktop/Code/dexie-vite-repro/node_modules/esbuild/lib/main.js:726:9)
    at Socket.readFromStdout (/Users/dustyphillips/Desktop/Code/dexie-vite-repro/node_modules/esbuild/lib/main.js:596:7)
    at Socket.emit (node:events:390:28)
    at addChunk (node:internal/streams/readable:324:12)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Note that I used Dexie 3.2.1-beta.2, as the error message is reminiscent of the two PRs mentioned in the release notes for it. I wondered if whatever the fix was for that release is also required for dexie cloud addon, but I haven't verified that.

**Comment by dfahlander** [comment]
Hi! Latest dexie-cloud beta needs dexie@4.0.0-alpha.1. Install it using `yarn add dexie@next`.

**Comment by dusty-phillips** [comment]
hm. I bumped dexie-cloud to 4.0.0-alpha.1, and the error has gone away. However, so has any good behaviour. I've pushed some commits to https://github.com/dusty-phillips/dexie-with-vite-repro illustrating. The key point is:

```
              // This promise never resolves, catches, or finallys
              db.count
                .add({ count: count + 1 })
                .then((i) => console.log("Count Success", i))
                .catch((e) => console.log("Count failure", e))
                .finally(() => console.log("Count finally"));
```

This may be a bug in Dexie, I have a feeling this is just me having done something silly in my configuration. I'm going to try building a Dexie-vite app from scratch and see if I get better behaviour. Will log here with any findings.

**Comment by dfahlander** [comment]
Ok thanks for the repro. I'll try to dive into it the coming days!

In latest version of dexie-cloud-addon, rxjs is changed to be a peerDependency instead of a normal dependency because it seems to be the recommended way for libraries, but it puts the responsibility on the user to add it instead of being auto resolved. I might have missed to update docs, sorry for that!

Still being a bit behind in docs, I will continuously make sure [the example app](https://github.com/dexie/Dexie.js/tree/master/samples/dexie-cloud-todo-app) is functional and up to date.

I'm eager to get to the bottom with why the put-operation gets stuck in this setup and hope to be able to respond to that issue soon.

**Comment by dfahlander** [comment]
I found the reason and am working on a fix. It's not about vite but rather the modern build of dexie-cloud-addon.

**Comment by dfahlander** [comment]
Still having other issue with this repro that I'm investigating

**Comment by hangtwenty** [comment]
On the latest `master` (ccde2952e5da5e0965a6009562e60524db3f8411), I'm getting the following when I try `dexie-cloud-todo-app` `npm run start`:

```
index.js:1 DexieError {_e: Error
    at getErrorWithStack (http://localhost:3000/static/js/vendors~main.chunk.js:26713:10)
   …, name: 'PrematureCommitError', message: 'Transaction committed too early. See http://bit.ly/2kdckMn', inner: null, _promise: DexiePromise, …}inner: nullmessage: "Transaction committed too early. See http://bit.ly/2kdckMn"name: "PrematureCommitError"_e: Error
    at getErrorWithStack (http://localhost:3000/static/js/vendors~main.chunk.js:26713:10)
    at new DexieError (http://localhost:3000/static/js/vendors~main.chunk.js:26791:15)
    at http://localhost:3000/static/js/vendors~main.chunk.js:30926:43
    at http://localhost:3000/static/js/vendors~main.chunk.js:27649:17
    at callListener (http://localhost:3000/static/js/vendors~main.chunk.js:27336:13)
    at endMicroTickScope (http://localhost:3000/static/js/vendors~main.chunk.js:27414:17)
    at IDBTransaction.<anonymous> (http://localhost:3000/static/js/vendors~main.chunk.js:27480:24)stack: "Error\n    at getErrorWithStack (http://localhost:3000/static/js/vendors~main.chunk.js:26713:10)\n    at new DexieError (http://localhost:3000/static/js/vendors~main.chunk.js:26791:15)\n    at http://localhost:3000/static/js/vendors~main.chunk.js:30926:43\n    at http://localhost:3000/static/js/vendors~main.chunk.js:27649:17\n    at callListener (http://localhost:3000/static/js/vendors~main.chunk.js:27336:13)\n    at endMicroTickScope (http://localhost:3000/static/js/vendors~main.chunk.js:27414:17)\n    at IDBTransaction.<anonymous> (http://localhost:3000/static/js/vendors~main.chunk.js:27480:24)"[[Prototype]]: Object_promise: DexiePromise {_listeners: Array(0), _lib: false, _PSD: {…}, _stackHolder: Error
    at getErrorWithStack (http://localhost:3000/static/js/vendors~main.chunk.js:26713:10)
   …, onuncatched: ƒ, …}stack: (...)get stack: ƒ ()[[Prototype]]: DexieError

console.<computed> | @ | index.js:1
  | (anonymous) | @ | dexie-cloud-addon.js:5831
  | step | @ | tslib.es6.js:102
  | (anonymous) | @ | tslib.es6.js:83
  | rejected | @ | dexie-cloud-addon.js:41
  | (anonymous) | @ | promise.js:845
  | callListener | @ | promise.js:502
  | endMicroTickScope | @ | promise.js:584
  | (anonymous) | @ | promise.js:653
```

<details><summary>Here's a screenshot of dexie-cloud-addon.js:5831</summary>

![image](https://user-images.githubusercontent.com/2420688/162838923-9dff7952-bace-4adb-b9d9-4e11c1d28422.png)

</details>

**Comment by hangtwenty** [comment]
Actually seem to still be getting that error when I try checking out older commits. So I'm not sure why, but I haven't been able to rewind to a state where `dexie-cloud-todo-app` works again (which should not be impacted by using vite; just trying to establish a working baseline again before I try the latest `dexie-cloud` with vite).

**Comment by dfahlander** [comment]
Latest master has a problem that was not detected in ordinary unit tests but ends up in PrematureCommitError.

I have reverted the npm dist-tag 'next' and pointed it back to dexie@4.0.0-alpha.1 to prohibit people from using dexie@4.0.0-alpha.2 until the problem has been solved.

I will also revert the failing commit for now in master while I try to examine the error.

**Comment by dfahlander** [comment]
On the other hand, the latest release of dexie-cloud-addon (4.0.0-beta.18) can be combined with dexie@4.0.0-alpha.1 and could be a solution to this issue.

**Comment by dusty-phillips** [comment]
cloud 4.0.0-beta.18 works with dexie@4.0.0-alpha.1 also works for me. Thanks!

**Comment by hangtwenty** [comment]
Checking back in: this has been working well for me too.

**Comment by dfahlander** [comment]
Closing as this issue was obviously fixed
