### ISSUE TITLE
reactivity - currentObs in live-query.ts always empty

### ISSUE THREAD

**Issue by gotjoshua** [dexie/Dexie.js#1526]
I have not been able to isolate this enough to create a minimal reproduction, but i am investigating as deeply as i can, and want to document that investigation here and to ask for assistance.

So, the subscription is firing, but shouldNotify() is failing because currentObs is an empty object.

I think something "impure" is supposed to happen to subscr [inside this call to exec](https://github.com/dexie/Dexie.js/blob/master/src/live-query/live-query.ts#L29):
```ts
const exec = () => newScope(querier, { subscr, trans: null });
```
i get an original result and rendering, but [this assignment to currentObs](https://github.com/dexie/Dexie.js/blob/master/src/live-query/live-query.ts#L101) is an empty object, thus should notify never has any keys to work with.

I tried to understand the inner workings of exec and newScope, but i didn't manage. Any hints how to debug this?

**Comment by gotjoshua** [comment]
I had one theory that it was due to compound keys, but [reactivity proved to be fine in this stackblitz.](https://stackblitz.com/edit/dexie-todo-list-fkd46f)

**Comment by gotjoshua** [comment]
at the bottom of newScope the return value for rv contains an error stack that never gets to the console:


```js
    at DexiePromise.then (https://unpkg.com/dexie@3.2.1/dist/dexie.mjs:657:22)
    at Collection._read (https://unpkg.com/dexie@3.2.1/dist/dexie.mjs:1861:46)
    at Collection.toArray (https://unpkg.com/dexie@3.2.1/dist/dexie.mjs:1930:21)
    at ActiveTasksQuery (http://localhost:3030/src/Data/data.ts:26:88)
    at usePSD (http://localhost:3030/node_modules/.vite/chunk-KKCCPCEG.js?v=7e184aee:758:12)
    at newScope (http://localhost:3030/node_modules/.vite/chunk-KKCCPCEG.js?v=7e184aee:665:12)
    at exec (http://localhost:3030/node_modules/.vite/chunk-KKCCPCEG.js?v=7e184aee:2642:16)
    at execute (http://localhost:3030/node_modules/.vite/chunk-KKCCPCEG.js?v=7e184aee:2644:58)
From previous: 
    at DexiePromise.then (https://unpkg.com/dexie@3.2.1/dist/dexie.mjs:657:22)
    at tempTransaction (https://unpkg.com/dexie@3.2.1/dist/dexie.mjs:1278:12)
    at Table._trans (https://unpkg.com/dexie@3.2.1/dist/dexie.mjs:1343:17)
    at Collection._read (https://unpkg.com/dexie@3.2.1/dist/dexie.mjs:1861:23)
    at Collection.toArray (https://unpkg.com/dexie@3.2.1/dist/dexie.mjs:1930:21)
    at ActiveTasksQuery (http://localhost:3030/src/Data/data.ts:26:88)
    at usePSD (http://localhost:3030/node_modules/.vite/chunk-KKCCPCEG.js?v=7e184aee:758:12)
    at newScope (http://localhost:3030/node_modules/.vite/chunk-KKCCPCEG.js?v=7e184aee:665:12)
From previous: 
    at Transaction._promise (https://unpkg.com/dexie@3.2.1/dist/dexie.mjs:2770:21)
    at tempTransaction (https://unpkg.com/dexie@3.2.1/dist/dexie.mjs:1273:22)
    at Table._trans (https://unpkg.com/dexie@3.2.1/dist/dexie.mjs:1343:17)
    at Collection._read (https://unpkg.com/dexie@3.2.1/dist/dexie.mjs:1861:23)
    at Collection.toArray (https://unpkg.com/dexie@3.2.1/dist/dexie.mjs:1930:21)
    at ActiveTasksQuery (http://localhost:3030/src/Data/data.ts:26:88)
    at usePSD (http://localhost:3030/node_modules/.vite/chunk-KKCCPCEG.js?v=7e184aee:758:12)
    at newScope (http://localhost:3030/node_modules/.vite/chunk-KKCCPCEG.js?v=7e184aee:665:12)
```

![dexieFromCDNstack](https://user-images.githubusercontent.com/8686454/160281944-b55b5681-5ee9-4ea6-9b82-692692c799be.png)


i guess this is where my reactivity is getting lost.

**Comment by gotjoshua** [comment]
further investigation has shown that importing via cdn, seems to break reactivity.
Stackblitz doesn't allow top level await, so i didn't manage to reproduce it there, but i have a local repo and will try to push a branch this week.

@dfahlander, can you think of a reason that PSD fails to update `subscr` when importing via cdn?
