### ISSUE TITLE
this.tables.mapToClass is not a function: only when table is named "tables", works with other names

### ISSUE THREAD

**Issue by barbalex** [dexie/Dexie.js#1537]
Here is where the db is initiated:
```ts
import Dexie, { DexieTable } from 'dexie'
import { v1 as uuidv1 } from 'uuid'


export class Table implements ITable {
  id: string
  project_id?: string
  parent_id?: string
  rel_type?: string
  name?: string
  label?: string
  single_label?: string
  label_fields?: string[]
  label_fields_separator?: string
  sort?: number
  option_type?: string
  client_rev_at?: Date
  client_rev_by?: string
  server_rev_at?: Date
  deleted?: boolean

  constructor(
    id?: string,
    project_id?: string,
    parent_id?: string,
    rel_type?: string,
    name?: string,
    label?: string,
    single_label?: string,
    label_fields?: string[],
    label_fields_separator?: string,
    sort?: number,
    option_type?: string,
    client_rev_at?: Date,
    client_rev_by?: string,
    server_rev_at?: Date,
    deleted?: boolean,
  ) {
    this.id = id ?? uuidv1()
    if (project_id) this.project_id = project_id
    if (parent_id) this.parent_id = parent_id
    if (rel_type) this.rel_type = rel_type
    if (name) this.name = name
    if (label) this.label = label
    if (single_label) this.single_label = single_label
    if (label_fields) this.label_fields = label_fields
    if (label_fields_separator)
      this.label_fields_separator = label_fields_separator
    if (sort) this.sort = sort
    if (option_type) this.option_type = option_type
    if (client_rev_at) this.client_rev_at = client_rev_at
    if (client_rev_by) this.client_rev_by = client_rev_by
    if (server_rev_at) this.server_rev_at = server_rev_at
    if (deleted) this.deleted = deleted
  }
}

export class MySubClassedDexie extends Dexie {
  tables!: DexieTable<Table, string>

  constructor() {
    super('capturing')
    this.version(1).stores({
      tables:
        'id, label, sort, project_id, parent_id, rel_type, option_type, server_rev_at',
    })
    this.tables.mapToClass(Table)
  }
}

export const db = new MySubClassedDexie()
```
(I removed all other tables to simplify)

This throws an error:
```
TypeError: this.tables.mapToClass is not a function
    at new MySubClassedDexie (webpack-internal:///./modules/initiateDb.ts:280:21)
    at eval (webpack-internal:///./modules/initiateDb.ts:286:12)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

When `tables` is renamed to anything else, like `ctables`, it works as expected.

What could be wrong?

dexie is used in v3.2.1.

**Comment by dfahlander** [comment]
[Dexie.tables](https://dexie.org/docs/Dexie/Dexie.tables) is an existing property on Dexie instances so there's a name conflict as you name your table "tables". Either name your table differently, or use `db.table('tables')` to access it.

**Comment by barbalex** [comment]
Thanks. And: Thanks so much for this GREAT tool
