### ISSUE TITLE
collection .ToArray() throws error

### ISSUE THREAD

**Issue by PacoRivera13** [dexie/Dexie.js#1555]
dexie": "3.0.1"
Using table.toArray() throws an error.
```
Error
    at getErrorWithStack (http://localhost:4200/vendor.js:486784:10)
    at new DexiePromise (http://localhost:4200/vendor.js:487082:25)
    at DexiePromise.then (http://localhost:4200/vendor.js:487111:16)
    at tempTransaction (http://localhost:4200/vendor.js:487795:8)
    at Table$$1.Table._trans (http://localhost:4200/vendor.js:487855:12)
    at Collection$$1.Collection._read (http://localhost:4200/vendor.js:488378:92)
    at Collection$$1.Collection.toArray (http://localhost:4200/vendor.js:488470:17)
    at eval (eval at push.53241.DataService.filter (http://localhost:4200/main.js:2326:9), <anonymous>:1:12)
    at DataService.push.53241.DataService.filter (http://localhost:4200/main.js:2326:9)
    at DataService.<anonymous> (http://localhost:4200/main.js:2272:57)
```

**Comment by dfahlander** [comment]
I'm sorry this issue does not give me any context. Closing.

**Comment by PacoRivera13** [comment]
Sorry, I forgot to add more context.
I was using "@angular/core": "11.2.0", I updated my project to "@angular/core": "12.2.16",
any method like .count() or toArray() stop working on my app. 

I got this
"Error
    at q (http://localhost:4200/vendor.js:486725:10)
    at new Ce (http://localhost:4200/vendor.js:486938:33)
    at Ce.n (http://localhost:4200/vendor.js:486956:15)
    at Rt._read (http://localhost:4200/vendor.js:488100:101)
    at Rt.count (http://localhost:4200/vendor.js:488144:19)
    at kt.count (http://localhost:4200/vendor.js:487616:34)
    at DataService.push.53241.DataService.filter (http://localhost:4200/main.js:2279:27)
    at DataService.<anonymous> (http://localhost:4200/main.js:2194:57)
    at step (http://localhost:4200/vendor.js:486256:23)
    at Object.next (http://localhost:4200/vendor.js:486237:53)"
