### ISSUE TITLE
Testing React components that use Dexie

### ISSUE THREAD

**Issue by Odisseus-sst** [dexie/Dexie.js#1601]
When using Dexie in a React + Typescript project I am getting a weird error from jest:

From my understanding this is caused by the fact that Dexie is being treated as an ESM.

```
    /Users/rareslungescu/Documents/Hosta-AI-Frontend/node_modules/dexie/dist/modern/dexie.mjs:5093
    export { Dexie$1 as Dexie, RangeSet, Dexie$1 as default, liveQuery, mergeRanges, rangesOverlap };
    ^^^^^^

    SyntaxError: Unexpected token 'export'

    > 1 | import Dexie, {Table} from 'dexie';
        | ^
      2 | export interface IPicture {
      3 |   id: number;
      4 |   content: string;

      at Runtime.createScriptFromCode (node_modules/jest-cli/node_modules/jest-runtime/build/index.js:1796:14)
      at Object.<anonymous> (src/utils/indexedDb.ts:1:1)

```

I tried a couple of things to fix this but with no luck:
1. Using the experimental jest esm compatibility
2. Trying to transform dexie and dexie-react-hooks with babel
3. Tried to import dexie with require

I would really appreciate some guidance on how to make my tests run again. Thanks!

Current environment:
Node v18.3.0
Typescript 4.7.4
Jest 28.12.2

**Comment by bmsrox** [comment]
Any solution? I have tried the same approachs.

**Comment by bmsrox** [comment]
I found this solution.

Add it to jest config file

```
moduleNameMapper: {
   ...
    '^dexie$': require.resolve('dexie'),
   ... 
  }
```

**Comment by im-adithya** [comment]
Ran into the same error here: https://github.com/getAlby/lightning-browser-extension/pull/1721
@-maintainers Is it possible to have Dexie as a compiled npm package to avoid this?

**Comment by dfahlander** [comment]
We use the "magical" `exports` field to allow bundlers the choice whether to import the legacy or modern version of dexie. Somehow the jest setup chooses the modern version of dexie but jest fails to run ESM modules (if I am not mistaken). However, using the exports-field to export multiple versions of a library conditionally seems to be a source of problems. Maybe it would have been better to stick to the old ES5 export. But at some point, we must move forward. If anyone has a better understanding of this, please let me know :)

**Comment by xavierrobitaille** [comment]
@bmsrox 's solution worked for me, although I had to tweak it ever so slightly because my jest config is in my package.json file:

```
  "jest": {
    "moduleNameMapper": {
      "^dexie$": "<rootDir>/node_modules/dexie"
    }
  },
```

Xavier
https://featherfinance.com
