### ISSUE TITLE
Dexie query Promise never resolves

### ISSUE THREAD

**Issue by lucassilvas1** [dexie/Dexie.js#1627]
I have this function:
```javascript
function updateDay(date, tasks) {
  return new Promise((res) => {
    console.log("updateDay", date);
    db.transaction("rw", db.tasks, db.projects, db.requesters, async (tx) => {
      console.log("Inside updateDay transaction callback for", date);
      const old = await db.tasks.where("date").equals(date).toArray(); // GETS STUCK HERE AT LINE 6
      console.log("Found tasks for", date, old.length); // I NEVER SEE THIS
      for (const task of tasks) {
        const oldTask = old.find((t) => t.assignment_id === task.assignment_id);
        if (!oldTask) task.date = date;
        else task = { ...oldTask, ...task };
        await updateTask(task);
      }
      await db.tasks.bulkPut(tasks);
      res();
    });
  });
}
```
And for some reason whenever I call it, it gets stuck at line 6, it never throws any error either, it just hangs there, indefinitely.

I'm new to Dexie and IndexedDB, can someone help me with this?

**To be clear:** `date` is a `string` such as "2022-10-11", `db.tasks` does exist and it does have a `date` index

**Comment by lucassilvas1** [comment]
Made a change to the function:
```javascript
function updateDay(date, tasks) {
  return new Promise((res) => {
    console.log("updateDay", date);
    db.transaction("rw", db.tasks, db.projects, db.requesters, async (tx) => {
      console.log("Inside updateDay transaction callback for", date);
      const result = await db.tasks.where("date").equals(date);
      console.log("result", result);
      let old;
      try {
        old = await result.toArray();
      } catch (error) {
        console.log(error);
        throw error;
      }
      console.log("Found tasks for", date, old);
      for (const task of tasks) {
        const oldTask = old.find((t) => t.assignment_id === task.assignment_id);
        if (!oldTask) task.date = date;
        else task = { ...oldTask, ...task };
        await updateTask(task);
      }
      await db.tasks.bulkPut(tasks);
      res();
    });
  });
}
```

And when calling it, this is what I get from the `console.log` inside the `catch` block: 
```
TypeError: Cannot read properties of undefined (reading 'schema')
    at dexie.mjs:1873:67
    at s (dexie.mjs:1294:20)
    at dexie.mjs:2685:26
    at tr (dexie.mjs:797:9)
    at new Zo (dexie.mjs:616:5)
    at js._promise (dexie.mjs:2684:21)
    at Zr._trans (dexie.mjs:1300:27)
    at ds._read (dexie.mjs:1802:23)
    at ds.toArray (dexie.mjs:1869:21)
    at js.<anonymous> (tasks.js:68:24)
```

Still don't know why this is happening, though.

**Comment by dfahlander** [comment]
Don't create a new Promise(). Exceptions will not be caught. Do this instead:

```ts
async function updateDay(date, tasks) {
  console.log("updateDay", date);
  await db.transaction("rw", db.tasks, db.projects, db.requesters, async (tx) => {
    ...
  });
}
```

Don't know the reason for undefined on line 1873 (reading table.core.schema). Can you share your declaration of db?

**Comment by lucassilvas1** [comment]
Sorry for the delay, I was asleep.
Here's the declaration of the db:
```javascript
import Dexie from "dexie";

const db = new Dexie("tracker");
db.version(1).stores({
  tasks: "assignment_id,state,title,hit_id,requester_name,requester_id,date",
  projects: "hit_id,title,requester_name,requester_id",
  requesters: "requester_id,requester_name",
});

export default db;
```

**Comment by lucassilvas1** [comment]
Never mind, I had added some methods to the prototype of `Object` called `deepCopy` and `resolve` and Dexie probably does the same thing, so I was overwriting them, removed the methods and now things are actually working.

**Comment by dfahlander** [comment]
> Never mind, I had added some methods to the prototype of `Object` called `deepCopy` and `resolve` and Dexie probably does the same thing, so I was overwriting them, removed the methods and now things are actually working.

Dexie.js does not extend Object.prototype, but I'm happy you could resolve the issue. I still have no explanation why this was happening, but generally, extending Object.prototype can lead to strange behaviour and it is best to avoid it if possible.
