### ISSUE TITLE
Is it possible to output more info when "Assertion Failed"?

### ISSUE THREAD

**Issue by paulrosen** [dexie/Dexie.js#1777]
I'm trying to hook up my dexie db to the cloud and got a bunch of promising output in the console, but then I started getting assertion errors. I have no info about what to look for. Here is the entirety of the message:
```
Failed to sync client changes Error: Assertion Failed
    at assert (utils.ts:71:19)
    at Dexie$1.setByKeyPath (utils.ts:138:9)
    at encodeIdsForServer.ts:38:19
    at Array.forEach (<anonymous>)
    at encodeIdsForServer.ts:29:16
    at Array.forEach (<anonymous>)
    at encodeIdsForServer (encodeIdsForServer.ts:25:10)
    at syncWithServer.ts:51:14
    at Generator.next (<anonymous>)
    at fulfilled (tslib.es6.js:73:58)
```
On the console before that I got lines starting with
SYNC STARTED
syncIfPossible
Sync request
BroadcastedAndLocalEvent
etc...
MORE SYNC NEEDED
SYNC STARTED
New Websocket Connection
dexie-cloud WebSocket create
Error from _sync (with the same assertion error)

How do I begin to debug this?

**Comment by dfahlander** [comment]
Thanks for the log printouts - seems as the problem is related a table with compound primary keys but the keys are not arrays as expected but plain strings. This could indicate a bug in dexie-cloud. I'll see if I can reproduce the issue from your database if I get a change tomorrow. You can export everything to a JSON file if that would help using [npx dexie-cloud@latest export](https://dexie.org/cloud/docs/cli#export). Compound primary keys are stored as JSON strings and it might be a problem with that. I might get wiser after looking into your db.

An admin dashboard with database and subscription management is under development as the last part before the service goes into production in the end of the summer. For now, it's only `npx dexie-cloud export` and the [REST API](https://dexie.org/cloud/docs/rest-api) available to inspect what's stored in the cloud.

**Comment by paulrosen** [comment]
[all-data.txt](https://github.com/dexie/Dexie.js/files/12254142/all-data.txt)

That is what export gives me - but did you want the contents of indexedDB instead? That is much larger.

**Comment by paulrosen** [comment]
A little more info:

I split the writes into sections and I successfully wrote all the MetaNames, Tunes, and Lists. That synced up properly.

But when I went to write TuneInList it started failing. That is doing a many-to-many relationship.

**Comment by dfahlander** [comment]
I found the issue and it's really a bug occurring when client is about to sync a table with inbound compound keys. I've release a new version with "test" tag for you to try out:

```
npm i dexie-cloud-addon@4.0.1-beta.46
```
Let me know if this fixes it.

Another thing I noticed is that the typings for IDs in your code are all numbers while they really should be strings ('@'-keys) and the relation table should be:

```ts
export class TuneInList {
        //id?: number; not there!
	tuneId: string; // not number
	listId: string; // not number
	order: number;
	constructor() {}
}
```

Please try out the fix and let me know if everything is working properly with it.

**Comment by paulrosen** [comment]
Yes! can confirm - it works. And I ran `npx dexie-cloud@latest export all-data.json` and all the data is there.
