### ISSUE TITLE
How to set Dexie.debug to true?

### ISSUE THREAD

**Issue by lucasrodrigues10** [dexie/Dexie.js#1806]
I'm using Dexie "3.2.1" and can't find a way to set **Dexie.debug** to **true**.

This is the docs which I used as reference.
https://dexie.org/docs/Dexie/Dexie.debug

Can you help me?

**Comment by dfahlander** [comment]
Typings are missing for Dexie.debug but it will respect it in regards of console logging. dexie-cloud-addon does not yet respect this value but a new version coming out soon will fix this. See #1801 .

**Comment by kheos31** [comment]
Hello @dfahlander !

I just saw this issue after I checked the typing and test on my own your enunciated solution.. But it doesn't work currently.. Or at least, it does not seem to have the behavior announced into the doc.

![image](https://github.com/dexie/Dexie.js/assets/130769302/8b28bceb-aae1-4263-a89f-e64182bdd968)

For example, this code with the valorization of debug at these 2 places, or using just one valorization or the other, give me this stack : 

`
An error was thrown in afterAll
Unhandled promise rejection: DataError: Failed to execute 'get' on 'IDBObjectStore': No key or key range specified.
 DataError: Failed to execute 'get' on 'IDBObjectStore': No key or key range specified.
error properties: Object({ _e: Error, inner: DataError: Failed to execute 'get' on 'IDBObjectStore': No key or key range specified., _promise: [object Dexie.Promise] })
Error: Failed to execute 'get' on 'IDBObjectStore': No key or key range specified.
    at fn (http://localhost:9876/_karma_webpack_/webpack:/node_modules/dexie/dist/modern/dexie.mjs:3153:39)
    at executePromiseTask (http://localhost:9876/_karma_webpack_/webpack:/node_modules/dexie/dist/modern/dexie.mjs:797:9)
    at new DexiePromise (http://localhost:9876/_karma_webpack_/webpack:/node_modules/dexie/dist/modern/dexie.mjs:616:5)
    at Object.apply (http://localhost:9876/_karma_webpack_/webpack:/node_modules/dexie/dist/modern/dexie.mjs:3150:24)
    at Object.get (http://localhost:9876/_karma_webpack_/webpack:/node_modules/dexie/dist/modern/dexie.mjs:4464:46)
    at fn (http://localhost:9876/_karma_webpack_/webpack:/node_modules/dexie/dist/modern/dexie.mjs:1313:30)
    at fn (http://localhost:9876/_karma_webpack_/webpack:/node_modules/dexie/dist/modern/dexie.mjs:1294:20)
    at fn (http://localhost:9876/_karma_webpack_/webpack:/node_modules/dexie/dist/modern/dexie.mjs:1237:24)
    at usePSD (http://localhost:9876/_karma_webpack_/webpack:/node_modules/dexie/dist/modern/dexie.mjs:1143:16)
    at newScope (http://localhost:9876/_karma_webpack_/webpack:/node_modules/dexie/dist/modern/dexie.mjs:1047:14)
From previous: 
    at Object.apply (http://localhost:9876/_karma_webpack_/webpack:/node_modules/dexie/dist/modern/dexie.mjs:3150:24)
    at Object.get (http://localhost:9876/_karma_webpack_/webpack:/node_modules/dexie/dist/modern/dexie.mjs:4464:46)
    at fn (http://localhost:9876/_karma_webpack_/webpack:/node_modules/dexie/dist/modern/dexie.mjs:1313:30)
    at fn (http://localhost:9876/_karma_webpack_/webpack:/node_modules/dexie/dist/modern/dexie.mjs:1294:20)
    at fn (http://localhost:9876/_karma_webpack_/webpack:/node_modules/dexie/dist/modern/dexie.mjs:1237:24)
    at usePSD (http://localhost:9876/_karma_webpack_/webpack:/node_modules/dexie/dist/modern/dexie.mjs:1143:16)
    at newScope (http://localhost:9876/_karma_webpack_/webpack:/node_modules/dexie/dist/modern/dexie.mjs:1047:14)
    at http://localhost:9876/_karma_webpack_/webpack:/node_modules/dexie/dist/modern/dexie.mjs:1235:20
Unhandled promise rejection: DataError: Failed to execute 'get' on 'IDBObjectStore': No key or key range specified.
 DataError: Failed to execute 'get' on 'IDBObjectStore': No key or key range specified.
error properties: Object({ _e: Error, inner: DataError: Failed to execute 'get' on 'IDBObjectStore': No key or key range specified., _promise: [object Dexie.Promise] })
Error: Failed to execute 'get' on 'IDBObjectStore': No key or key range specified.
    at fn (http://localhost:9876/_karma_webpack_/webpack:/node_modules/dexie/dist/modern/dexie.mjs:3153:39)
    at executePromiseTask (http://localhost:9876/_karma_webpack_/webpack:/node_modules/dexie/dist/modern/dexie.mjs:797:9)
    at new DexiePromise (http://localhost:9876/_karma_webpack_/webpack:/node_modules/dexie/dist/modern/dexie.mjs:616:5)
    at Object.apply (http://localhost:9876/_karma_webpack_/webpack:/node_modules/dexie/dist/modern/dexie.mjs:3150:24)
    at Object.get (http://localhost:9876/_karma_webpack_/webpack:/node_modules/dexie/dist/modern/dexie.mjs:4464:46)
    at fn (http://localhost:9876/_karma_webpack_/webpack:/node_modules/dexie/dist/modern/dexie.mjs:1313:30)
    at fn (http://localhost:9876/_karma_webpack_/webpack:/node_modules/dexie/dist/modern/dexie.mjs:1294:20)
    at fn (http://localhost:9876/_karma_webpack_/webpack:/node_modules/dexie/dist/modern/dexie.mjs:1237:24)
    at usePSD (http://localhost:9876/_karma_webpack_/webpack:/node_modules/dexie/dist/modern/dexie.mjs:1143:16)
    at newScope (http://localhost:9876/_karma_webpack_/webpack:/node_modules/dexie/dist/modern/dexie.mjs:1047:14)
From previous: 
    at Object.apply (http://localhost:9876/_karma_webpack_/webpack:/node_modules/dexie/dist/modern/dexie.mjs:3150:24)
    at Object.get (http://localhost:9876/_karma_webpack_/webpack:/node_modules/dexie/dist/modern/dexie.mjs:4464:46)
    at fn (http://localhost:9876/_karma_webpack_/webpack:/node_modules/dexie/dist/modern/dexie.mjs:1313:30)
    at fn (http://localhost:9876/_karma_webpack_/webpack:/node_modules/dexie/dist/modern/dexie.mjs:1294:20)
    at fn (http://localhost:9876/_karma_webpack_/webpack:/node_modules/dexie/dist/modern/dexie.mjs:1237:24)
    at usePSD (http://localhost:9876/_karma_webpack_/webpack:/node_modules/dexie/dist/modern/dexie.mjs:1143:16)
    at newScope (http://localhost:9876/_karma_webpack_/webpack:/node_modules/dexie/dist/modern/dexie.mjs:1047:14)
    at http://localhost:9876/_karma_webpack_/webpack:/node_modules/dexie/dist/modern/dexie.mjs:1235:20
Unhandled promise rejection: DataError: Failed to execute 'get' on 'IDBObjectStore': No key or key range specified.
 DataError: Failed to execute 'get' on 'IDBObjectStore': No key or key range specified.
error properties: Object({ _e: Error, inner: DataError: Failed to execute 'get' on 'IDBObjectStore': No key or key range specified., _promise: [object Dexie.Promise] })
Error: Failed to execute 'get' on 'IDBObjectStore': No key or key range specified.
    at fn (http://localhost:9876/_karma_webpack_/webpack:/node_modules/dexie/dist/modern/dexie.mjs:3153:39)
    at executePromiseTask (http://localhost:9876/_karma_webpack_/webpack:/node_modules/dexie/dist/modern/dexie.mjs:797:9)
    at new DexiePromise (http://localhost:9876/_karma_webpack_/webpack:/node_modules/dexie/dist/modern/dexie.mjs:616:5)
    at Object.apply (http://localhost:9876/_karma_webpack_/webpack:/node_modules/dexie/dist/modern/dexie.mjs:3150:24)
    at Object.get (http://localhost:9876/_karma_webpack_/webpack:/node_modules/dexie/dist/modern/dexie.mjs:4464:46)
    at fn (http://localhost:9876/_karma_webpack_/webpack:/node_modules/dexie/dist/modern/dexie.mjs:1313:30)
    at fn (http://localhost:9876/_karma_webpack_/webpack:/node_modules/dexie/dist/modern/dexie.mjs:1294:20)
    at fn (http://localhost:9876/_karma_webpack_/webpack:/node_modules/dexie/dist/modern/dexie.mjs:1237:24)
    at usePSD (http://localhost:9876/_karma_webpack_/webpack:/node_modules/dexie/dist/modern/dexie.mjs:1143:16)
    at newScope (http://localhost:9876/_karma_webpack_/webpack:/node_modules/dexie/dist/modern/dexie.mjs:1047:14)
From previous: 
    at Object.apply (http://localhost:9876/_karma_webpack_/webpack:/node_modules/dexie/dist/modern/dexie.mjs:3150:24)
    at Object.get (http://localhost:9876/_karma_webpack_/webpack:/node_modules/dexie/dist/modern/dexie.mjs:4464:46)
    at fn (http://localhost:9876/_karma_webpack_/webpack:/node_modules/dexie/dist/modern/dexie.mjs:1313:30)
    at fn (http://localhost:9876/_karma_webpack_/webpack:/node_modules/dexie/dist/modern/dexie.mjs:1294:20)
    at fn (http://localhost:9876/_karma_webpack_/webpack:/node_modules/dexie/dist/modern/dexie.mjs:1237:24)
    at usePSD (http://localhost:9876/_karma_webpack_/webpack:/node_modules/dexie/dist/modern/dexie.mjs:1143:16)
    at newScope (http://localhost:9876/_karma_webpack_/webpack:/node_modules/dexie/dist/modern/dexie.mjs:1047:14)
    at http://localhost:9876/_karma_webpack_/webpack:/node_modules/dexie/dist/modern/dexie.mjs:1235:20
Unhandled promise rejection: DataError: Failed to execute 'get' on 'IDBObjectStore': No key or key range specified.
 DataError: Failed to execute 'get' on 'IDBObjectStore': No key or key range specified.
error properties: Object({ _e: Error, inner: DataError: Failed to execute 'get' on 'IDBObjectStore': No key or key range specified., _promise: [object Dexie.Promise] })
Error: Failed to execute 'get' on 'IDBObjectStore': No key or key range specified.
    at fn (http://localhost:9876/_karma_webpack_/webpack:/node_modules/dexie/dist/modern/dexie.mjs:3153:39)
    at executePromiseTask (http://localhost:9876/_karma_webpack_/webpack:/node_modules/dexie/dist/modern/dexie.mjs:797:9)
    at new DexiePromise (http://localhost:9876/_karma_webpack_/webpack:/node_modules/dexie/dist/modern/dexie.mjs:616:5)
    at Object.apply (http://localhost:9876/_karma_webpack_/webpack:/node_modules/dexie/dist/modern/dexie.mjs:3150:24)
    at Object.get (http://localhost:9876/_karma_webpack_/webpack:/node_modules/dexie/dist/modern/dexie.mjs:4464:46)
    at fn (http://localhost:9876/_karma_webpack_/webpack:/node_modules/dexie/dist/modern/dexie.mjs:1313:30)
    at fn (http://localhost:9876/_karma_webpack_/webpack:/node_modules/dexie/dist/modern/dexie.mjs:1294:20)
    at fn (http://localhost:9876/_karma_webpack_/webpack:/node_modules/dexie/dist/modern/dexie.mjs:1237:24)
    at usePSD (http://localhost:9876/_karma_webpack_/webpack:/node_modules/dexie/dist/modern/dexie.mjs:1143:16)
    at newScope (http://localhost:9876/_karma_webpack_/webpack:/node_modules/dexie/dist/modern/dexie.mjs:1047:14)
From previous: 
    at Object.apply (http://localhost:9876/_karma_webpack_/webpack:/node_modules/dexie/dist/modern/dexie.mjs:3150:24)
    at Object.get (http://localhost:9876/_karma_webpack_/webpack:/node_modules/dexie/dist/modern/dexie.mjs:4464:46)
    at fn (http://localhost:9876/_karma_webpack_/webpack:/node_modules/dexie/dist/modern/dexie.mjs:1313:30)
    at fn (http://localhost:9876/_karma_webpack_/webpack:/node_modules/dexie/dist/modern/dexie.mjs:1294:20)
    at fn (http://localhost:9876/_karma_webpack_/webpack:/node_modules/dexie/dist/modern/dexie.mjs:1237:24)
    at usePSD (http://localhost:9876/_karma_webpack_/webpack:/node_modules/dexie/dist/modern/dexie.mjs:1143:16)
    at newScope (http://localhost:9876/_karma_webpack_/webpack:/node_modules/dexie/dist/modern/dexie.mjs:1047:14)
    at http://localhost:9876/_karma_webpack_/webpack:/node_modules/dexie/dist/modern/dexie.mjs:1235:20
`

No info for the origin of this error in my own code. Is it normal? Does I valorized the property badly?

NB: I found finally the problem after a little day lost on my own bad code, but I would prefer an info about the source caller if this kind of error will be produced..

Thanks in advance.

**Comment by dfahlander** [comment]
Thanks! This kind of error should be validated earlier in Table.get() to prohibit this kind of native error happening deep within dexie. The async call stack doesn't reveal much. Would also want to look into how Dexie could use Chrome's new [async stack tagging Api](https://developer.chrome.com/blog/devtools-modern-web-debugging/#linked_stack_traces) do improve the call stack.

**Comment by kheos31** [comment]
Thanks for response, sounds great for the future so! :D 
Thanks for this great lib and impatient to try Dexie 4 and discover all new features!
