### ISSUE TITLE
"default" is not exported by "../../../Dexie.js/dist/dexie.min.js", imported by "../../../Dexie.js/import-wrapper-prod.mjs".

### ISSUE THREAD

**Issue by nlaurie** [dexie/Dexie.js#1995]
When building via Vite.  Getting 

`
x Build failed in 8.15s
error during build:
RollupError: [vite-plugin-pwa:build] ../../../Dexie.js/import-wrapper-prod.mjs (4:7): "default" is not exported by "../../../Dexie.js/dist/dexie.min.js", imported by "../../../Dexie.js/import-wrapper-prod.mjs".
file: /Users/nlaurie/Development/metafig/Dexie.js/import-wrapper-prod.mjs:4:7
`

Everything go back to building fine when I revert to a previous package.json that looks like this

`
      "production": {
        "module": "./import-wrapper-prod.mjs",
        "import": "./import-wrapper-prod.mjs",
        "require": "./dist/dexie.min.js",
        "default": "./dist/dexie.min.js"
      },
`

**Comment by dfahlander** [comment]
How does the non-working package.json look? When I look at current one, it has

```
      "production": {
        "module": "./import-wrapper-prod.mjs",
        "import": "./import-wrapper-prod.mjs",
        "require": "./dist/dexie.min.js",
        "default": "./dist/dexie.min.js"
      },
```

Seems identical?

**Comment by nlaurie** [comment]
Left Non Working,  Right Working

![image](https://github.com/dexie/Dexie.js/assets/10317679/fd2dbf1c-8cc0-47c1-9178-d5b61cae1c25)

**Comment by nlaurie** [comment]
It was a couple months back when the issue cropped in when the wrapper was introduced, I figured it would come up and get fixed with the release of 4.  I went through our code and made sure all the imports were consistent.  since I've seen this sort of error with libraries that dont have default exports and not using the * notation for the import.  import * as xyx from 'lib',  but Dexie has default exports.   so were using      import Dexie from 'dexie'

**Comment by dfahlander** [comment]
Tried to reproduce just now: https://github.com/dfahlander/dexie-vite-starter
I get it working with a clean vite project with typescript / react and adding dexie and using dexie-react-hooks,

But I saw there was an issue in vite https://github.com/vitejs/vite/issues/2679

Which version of vite are you using?

**Comment by nlaurie** [comment]
Vite 5.2.11

I switched the wrappers to , and its building with the configuration.  Shouldn't the import and browser be using the modern ESM build?
![image](https://github.com/dexie/Dexie.js/assets/10317679/1dbd7ed9-7c2d-4040-8d63-f740d4b8222c)

**Comment by dfahlander** [comment]
If we do, nextjs apps suffer from double instanciating the dexie module (for some reason) and that causes problems as it has static properties that must be singleton instance. Ideally one should isolate state into a stateful module and import that one only as commonjs and the rest as ES.

**Comment by nlaurie** [comment]
I think I have it.  my project is pure ESM 
type: "module"

As per  https://nodejs.org/api/packages.html#dual-package-hazard

`
The preceding example uses explicit extensions .mjs and .cjs. If your files use the .js extension, "type": "module" will cause such files to be treated as ES modules, just as "type": "commonjs" would cause them to be treated as CommonJS. See
`

your load in the wrapper needs to be expliclity  [.cjs] in order for this technique not to blow up on pure ES projects.
import _Dexie from "./dist/dexie.min.cjs";

Which is why its importing as a ES and not commonjs resulting in default export not found.

**Comment by dfahlander** [comment]
Thanks for this finding. Not sure how to properly proceed though. The path dist/dexie.min.js is expected to be there by other docs and samples, for example when including dexie in a legacy script include.

I wonder if adding {"type": "commonjs"} in dexie's package.json would fix it. However, I would suppose "commonjs" is the default when "type" isn't specified so I'm not sure why vite is applying your project's "type" into dexie's type... I would suppose that vite is doing it wrong in that respect. This is a really mined area where any change can get things blown up for various configurations. I really regret adopting es module format too early, it has cause so much problems so far.

**Comment by nlaurie** [comment]
Here is the rub,  We unlinked from our fork [](https://github.com/metafig/Dexie.js) and reverted to the npm release. (built and ran as expected)  

It must be something specific to loading directly off the locally built fork.   (Which sucks cause it hinders our ability to help contribute to issues.) 

Were still running off our fork [](https://github.com/metafig/dexie-encrypted) so we can that project moving forward. 

I added the local pnpm link into your starter project and it failed as expected.
[](https://github.com/metafig/dexie-vite-starter)

**Comment by dfahlander** [comment]
I see. Seems as a vite bug then. Would it be a way forward if your fork of Dexie.js would have a step in its build process to copy dexie.min.js to dexie.min.cjs and change package.json?

**Comment by KittenApps** [comment]
Getting the same error here using rollup (in esm only mode) directly?

Could you maybe just add `"./dist/dexie.mjs": "./dist/dexie.mjs"` to the `package.json` export field, so can `import("dexie/dist/dexie.mjs")` directly without gettin a ` Could not resolve import "dexie/dist/dexie.mjs" in [...] using exports defined in [...]/node_modules/dexie/package.json.` error.

**Comment by rednil** [comment]
I have the same problem in a pure ESM project, no frameworks or packaging involved. I just updated from 3.2.2 to 4.0.7, now I am getting

> Uncaught (in promise) 
> SyntaxError: The requested module './dist/dexie.js' does not provide an export named 'default' (at ￼import-wrapper.mjs:4:8)

in the browser console.
I am just consuming dexie as a module via
`import Dexie from 'dexie'`

**Comment by dfahlander** [comment]
> I have the same problem in a pure ESM project, no frameworks or packaging involved. I just updated from 3.2.2 to 4.0.7, now I am getting
> 
> > Uncaught (in promise)
> > SyntaxError: The requested module './dist/dexie.js' does not provide an export named 'default' (at ￼import-wrapper.mjs:4:8)
> 
> in the browser console. I am just consuming dexie as a module via `import Dexie from 'dexie'`

Pure esm cannot load cjs modules. Import-wrapper is a workaround for node-based clients to avoid dual package hazard. For pure esm clients, import dist/dexie.mjs or dist/modern/dexie.mjs

**Comment by tobiasBora** [comment]
Not sure to understand, is there a solution to this problem? I need to maintain my own fork, at least until https://github.com/dexie/Dexie.js/pull/1973 gets merged, and I have no idea how to make `npm build` work…

**Comment by KittenApps** [comment]
change your imports from `dexie` to `dexie/dist/dexie.mjs"`

**Comment by tobiasBora** [comment]
Great thanks a lot, I thought this would only apply for a specific way of compiling… And it actually solves multiple weird bugs, including a really weird bug that my system was not using the proper Dexie version. I actually changed it globally by adding in my vite.config.ts:
```
export default defineConfig({
  resolve: {
    alias: {
      'dexie': 'dexie/dist/dexie.mjs',
      'dexie-export-import': 'dexie-export-import/dist/dexie-export-import.mjs'
    }
  },
});
```
Thanks!
